# dependabot.yml

---
name: Dependency Update

on:
  schedule:
    - cron: "0 0 * * 0"  # Run every Sunday at midnight
  workflow_dispatch:  # Manually triggered

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Dependabot Update
        uses: dependabot/dependabot-core@v2
